
name: Build and deploy to zerops.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - name: install, build, deploy  
      env: 
        ZEROPSTOKEN: ${{ secrets.ZEROPSTOKEN }}       
      run: |
        npm i -g @zerops/cli
        npm ci
        npm run build:all
        # download CLI, save as zcli, set permissions
#        wget -O zcli https://github.com/zeropsio/zcli/releases/download/v0.4.4/zcli-linux && chmod +x zcli        
 #       ./zcli login
  #      ./zcli deploy test-app nodejs0 .

