
name: Build and deploy to zerops.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2     
    - uses: zeropsio/zcli-action@v1
    - name: install, build, deploy  
      env: 
        ZEROPSTOKEN: ${{ secrets.ZEROPSTOKEN }}       
      run: |
        npm i -g @zerops/zcli
        npm ci
        npm run build:app
        zcli login
        zcli deploy test web dist/app/*

